2020-05-07 20:00:01,184 - Iniciando el proceso...
2020-05-07 20:00:01,184 - Escrapeando página web...
2020-05-07 20:00:13,055 - Obteniendo fecha y hora actual...
2020-05-07 20:00:13,056 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-07 20:01:01,355 - Iniciando el proceso...
2020-05-07 20:01:01,355 - Escrapeando página web...
2020-05-07 20:01:12,540 - Obteniendo fecha y hora actual...
2020-05-07 20:01:12,541 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-07 20:02:01,749 - Iniciando el proceso...
2020-05-07 20:02:01,749 - Escrapeando página web...
2020-05-07 20:02:13,708 - Obteniendo fecha y hora actual...
2020-05-07 20:02:13,708 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-07 20:03:01,909 - Iniciando el proceso...
2020-05-07 20:03:01,909 - Escrapeando página web...
2020-05-07 20:03:13,018 - Obteniendo fecha y hora actual...
2020-05-07 20:03:13,018 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-07 20:04:01,223 - Iniciando el proceso...
2020-05-07 20:04:01,223 - Escrapeando página web...
2020-05-07 20:04:16,287 - Obteniendo fecha y hora actual...
2020-05-07 20:04:16,287 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-07 20:05:01,496 - Iniciando el proceso...
2020-05-07 20:05:01,496 - Escrapeando página web...
2020-05-07 20:05:13,176 - Obteniendo fecha y hora actual...
2020-05-07 20:05:13,176 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-07 20:06:01,386 - Iniciando el proceso...
2020-05-07 20:06:01,386 - Escrapeando página web...
2020-05-07 20:06:12,789 - Obteniendo fecha y hora actual...
2020-05-07 20:06:12,790 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-07 20:07:02,043 - Iniciando el proceso...
2020-05-07 20:07:02,043 - Escrapeando página web...
2020-05-07 20:07:13,322 - Obteniendo fecha y hora actual...
2020-05-07 20:07:13,322 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 16:58:01,792 - Iniciando el proceso...
2020-05-08 16:58:01,792 - Escrapeando página web...
2020-05-08 16:58:12,724 - Obteniendo fecha y hora actual...
2020-05-08 16:58:12,725 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 16:59:01,162 - Iniciando el proceso...
2020-05-08 16:59:01,163 - Escrapeando página web...
2020-05-08 16:59:12,401 - Obteniendo fecha y hora actual...
2020-05-08 16:59:12,402 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:00:01,609 - Iniciando el proceso...
2020-05-08 17:00:01,609 - Escrapeando página web...
2020-05-08 17:00:12,877 - Obteniendo fecha y hora actual...
2020-05-08 17:00:12,877 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:01:01,844 - Iniciando el proceso...
2020-05-08 17:01:01,845 - Escrapeando página web...
2020-05-08 17:01:12,444 - Obteniendo fecha y hora actual...
2020-05-08 17:01:12,444 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:02:02,912 - Iniciando el proceso...
2020-05-08 17:02:02,913 - Escrapeando página web...
2020-05-08 17:04:03,522 - Obteniendo fecha y hora actual...
2020-05-08 17:04:03,523 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:06:02,400 - Iniciando el proceso...
2020-05-08 17:06:02,400 - Escrapeando página web...
2020-05-08 17:06:14,662 - Obteniendo fecha y hora actual...
2020-05-08 17:06:14,662 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:07:01,941 - Iniciando el proceso...
2020-05-08 17:07:01,942 - Escrapeando página web...
2020-05-08 17:07:14,054 - Obteniendo fecha y hora actual...
2020-05-08 17:07:14,054 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:19:01,292 - Iniciando el proceso...
2020-05-08 17:19:01,293 - Escrapeando página web...
2020-05-08 17:19:13,849 - Obteniendo fecha y hora actual...
2020-05-08 17:19:13,849 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:20:02,051 - Iniciando el proceso...
2020-05-08 17:20:02,051 - Escrapeando página web...
2020-05-08 17:20:12,628 - Obteniendo fecha y hora actual...
2020-05-08 17:20:12,628 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:21:01,830 - Iniciando el proceso...
2020-05-08 17:21:01,830 - Escrapeando página web...
2020-05-08 17:21:20,626 - Obteniendo fecha y hora actual...
2020-05-08 17:21:20,627 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/api-twitter/titulares.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/api-twitter/titulares.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:30:01,839 - Iniciando el proceso...
2020-05-08 17:30:01,840 - Escrapeando página web...
2020-05-08 17:30:14,052 - Obteniendo fecha y hora actual...
2020-05-08 17:30:14,053 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/python-for-everybody/using-databases/publish_titular.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/python-for-everybody/using-databases/publish_titular.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:31:01,298 - Iniciando el proceso...
2020-05-08 17:31:01,298 - Escrapeando página web...
2020-05-08 17:31:12,951 - Obteniendo fecha y hora actual...
2020-05-08 17:31:12,952 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/python-for-everybody/using-databases/publish_titular.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/python-for-everybody/using-databases/publish_titular.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:44:01,180 - Iniciando el proceso...
2020-05-08 17:44:01,180 - Escrapeando página web...
2020-05-08 17:44:36,043 - Obteniendo fecha y hora actual...
2020-05-08 17:44:36,044 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/python-for-everybody/using-databases/publish_titular.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/python-for-everybody/using-databases/publish_titular.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:45:01,263 - Iniciando el proceso...
2020-05-08 17:45:01,264 - Escrapeando página web...
2020-05-08 17:45:13,597 - Obteniendo fecha y hora actual...
2020-05-08 17:45:13,598 - Insertando datos en base de datos...
Traceback (most recent call last):
  File "/home/mati/Documentos/python-for-everybody/using-databases/publish_titular.py", line 53, in <module>
    insert_headlines_into_db(headlines_1)
  File "/home/mati/Documentos/python-for-everybody/using-databases/publish_titular.py", line 48, in insert_headlines_into_db
    ( titular, current_fecha,value,'El país' ) )
sqlite3.OperationalError: no such table: titulares
2020-05-08 17:53:01,820 - Iniciando el proceso...
2020-05-08 17:53:01,821 - Escrapeando página web...
2020-05-08 17:53:16,749 - Obteniendo fecha y hora actual...
2020-05-08 17:53:16,749 - Insertando datos en base de datos...
2020-05-08 17:53:33,352 - Proceso de base de datos finalizado.
2020-05-08 17:53:34,379 - Publicación exitosa.
2020-05-08 17:54:01,509 - Iniciando el proceso...
2020-05-08 17:54:01,509 - Escrapeando página web...
2020-05-08 17:54:13,449 - Obteniendo fecha y hora actual...
2020-05-08 17:54:13,449 - Insertando datos en base de datos...
2020-05-08 17:54:29,833 - Proceso de base de datos finalizado.
2020-05-08 17:54:30,378 - Titular duplicado no se pudo publicar.
2020-05-08 18:00:01,521 - Iniciando el proceso...
2020-05-08 18:00:01,522 - Escrapeando página web...
2020-05-08 18:00:12,168 - Obteniendo fecha y hora actual...
2020-05-08 18:00:12,169 - Insertando datos en base de datos...
2020-05-08 18:00:27,595 - Proceso de base de datos finalizado.
2020-05-08 18:00:28,190 - Publicación exitosa.
